apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "helm.fullname" . }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}
data:
  domain: {{ include .Values.domain . }}
  region: {{ include.Values.aws.region . }}
