apiVersion: v1
kind: Secret
metadata:
  name: {{ include "helm.fullname" . }}
type: Opaque
data:
  domain: {{ .Values.domainName | toString | b64enc }}
  aws_access_key: {{ .Values.aws.access_key | toString | b64enc }}
  aws_secret_key: {{ .Values.aws.secret_key | toString | b64enc }}
  aws_region: {{ .Values.aws.region | toString | b64enc }}
  ip_address: {{ .Values.ip_address | toString | b64enc }}
  {{- if .Values.namespace }}
  namespace: {{ .Values.namespace | toString | b64enc }}
  {{- end }}
