apiVersion: v1
kind: Secret
metadata:
  name: {{ include "helm.fullname" . }}
type: Opaque
data:
  domain: {{ include .Values.domain }}
  aws_access_key: {{ include .Values.aws.access_key . }}
  aws_secret_key: {{ include .Values.aws.secret_key . }}
  aws_region: {{ include .Values.aws.region . }}
  ip_address: {{ include .Values.ip_address . }}
  {{ if .Values.namespace }}
  namespace: {{ include .Values.namespace . }}
  {{ end }}
